### PR TITLE
Automatically open index files

### PR DESCRIPTION
**Pull request by tim-elmer**
Open an "index.htm", "index.html", or "index.php" in the current $_browse directory if present and enabled with $openIndex.

### CODE REVIEW

**Comment by lorenzos** [comment]
Thank you! I like the idea, but there's two things I wanted to be fixed before merging:

1. This is a bug I just noticed in my old code: looks like sub-folders browsing is possible also if `$browseDirectories = false`. One just needs to add `&b=subfolder` in the URL to be able to list files in any descendent directory. `$browseDirectories` is currently used only to change folders link. The fix is trivial: in line 33 we need a check before setting the `$_browse` variable. If you want to include this in the PR you're welcome.

```php
// Directory browsing
$_browse = null;
if ($browseDirectories) {
	$_GET['b'] = ...
```

Also, you should add a check in your code in line 40:

```php
if (!empty($_browse) && $openIndex) {
	...
```

2. I'd make it clear that the new `$openIndex` configuration is valid only when `$browseDirectories` is `true`. This can be said explicitly in the configuration comment, or implicitly in the assignment (I prefer):

```php
$openIndex = $browseDirectories && true; // Open index files present in the current directory
```

**Comment by tim-elmer** [comment]
Addressed by 97e904e, also fixes #6.

**Comment by lorenzos** [comment]
Thank you!

**Comment by lorenzos** [comment]
I just fixed a couple of stuffs on top of your PR, if you'd like to update your fork: 
https://github.com/lorenzos/Minixed/commits/master

**Pull request merged**
